INSERT INTO RATING (RATING_MPA_NAME)
VALUES ('G');

INSERT INTO RATING (RATING_MPA_NAME)
VALUES ('PG');

INSERT INTO RATING (RATING_MPA_NAME)
VALUES ('PG-13');

INSERT INTO RATING (RATING_MPA_NAME)
VALUES ('R');

INSERT INTO RATING (RATING_MPA_NAME)
VALUES ('NC-17');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Комедия');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Драма');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Мультфильм');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Триллер');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Документальный');

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Боевик');